### PR TITLE
Feat Security CRUD roles

### PR DESCRIPTION
**Pull request by gabiwassan**
Hi team,
This PR added new CRUD of Roles on the security section.

Added `securityService.js` with all requests centralized.

image

image

image

Searcher on multiselect component:
image

Delete sections with confirmation:
image

Closes: #1151

### CODE REVIEW

**Comment by eze9252** [comment]
Review:
- Search input doesnt work.
- When edit polices in a role, show the next message "The specified role-policy link already exist".
- Create and edit role UI view should be the same as the other sections.

**Comment by Desvelao** [comment]
**review**:

Testing:
- Table
  - List roles ✅ 
  **suggestion**: use `Policies` instead of `policies` for the column name. Is there some limitation to doing this?
  **suggestion**: use the policy name instead of its ID in the role mapping table
  image
  - Manage columns visibility ✅ 
  - Search ✅ 
  - `action:edit` (open the editing view) ✅ 
  - `action:delete` ❓ I could not test to delete a role due I could create the role from UI.
  **suggestion**: The prebuilt roles can't be removed, we should not have the `delete` button to these roles. (Its `ID` is lower than `100`)
- Add new role
  - Policy multi-select ✅
  - `action:save` :x:
  **issue**: There is an error
  image

**Comment by AlexRuiz7** [comment]
Policies assigned to reserved roles are hard to read. Long policies also overflow causing an ellipisis. There is plenty of space, so I'd make it biggger (currently has 200px, **250px works fine**)

image

In my opinion, I think the design looks better with some little adjustements, as follows:
image

- div containing the role name label and input:
```css
display: flex;
flex-direction: column;
```
- New role name input field:
```css
width: 250px !important;
margin-top: 5px;
```
- div containing the policies:
```css
width: 250px;
```
The buttons could be moved closer to the boxes on this design, so the user does not need to move along the whole view to click on them.

**Comment by AlexRuiz7** [comment]
## Disabled button style (general style)
It currently looks like this, shows a "not allowed" icon on hover, but it's hard to distinguish that it is disabled at first sight
image

As an improvement, our disabled buttons could use a grey-ish background color, like this:
image

**Comment by AlexRuiz7** [comment]
Still few things to fix:

* The `policies` column should be capitalized, as @Desvelao noted before: `Policies`
* The reserved policies should not shown a Delete or Edit button / icon. A chip with a `Reserved` text could be used instead.
* The style changes for the disabled buttons does also apply to **enabled** buttons now. 
  * Policies > Add new policy > See `Save`  button

**Comment by gabiwassan** [comment]
> Still few things to fix:
> 
> * The `policies` column should be capitalized, as @Desvelao noted before: `Policies`
> * The reserved policies should not shown a Delete or Edit button / icon. A chip with a `Reserved` text could be used instead.
> * The style changes for the disabled buttons does also apply to **enabled** buttons now.
>   
>   * Policies > Add new policy > See `Save`  button

Applied these suggestions! 👍🏼 

image

**Comment by AlexRuiz7** [comment]
Great improvements so far, unfortunately looks like the errors appeare

- Last reserved policy shows edit / delete actions
- Add new role has broken down.

Policies

**Review by yenienserrano — APPROVED** [review]
CR: heavy_check_mark
Test: heavy_check_mark

**Comment by eze9252** [comment]
CR: heavy_check_mark

Test: heavy_check_mark

**Comment by eze9252** [comment]
CR: OK

**Review by eze9252 — APPROVED** [review]

**Pull request merged**
