### PR TITLE
Mitre integration  - Dashboard

### LINKED ISSUE #884: MITRE integration  - Dashboards
Hi team,

We need to implement a new integration with MITRE adding a new dashboard for those alerts.

Core issue https://github.com/wazuh/wazuh/issues/3709

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this creates MITRE ATT&CK Dashboard view.

Closes #884 

image

### CODE REVIEW

**Comment by Machi3mfl** [comment]
I tried adding some alerts. 
Screen Shot 2021-04-27 at 12 31 11

I found a tooltip error in `Attack by techniques chart`
Screen Shot 2021-04-27 at 12 40 31

**Review by CPAlejandro — CHANGES_REQUESTED** [review]
Great job.
Here are a couple of improvements / bugs:
- When selecting a field of any visualization, the tooltip that appears covers most of it being quite uncomfortable.
image
- When you refresh a view, all of them are refreshed, not just the one you select.
- When generating a pdf, in each graph, in the right margin at the bottom, a black bar appears.
image

**Comment by Desvelao** [comment]
I was testing the PR and I am not experiencing the bug with the reports:

image

Possible bugs:
- Should the Mitre module appear by default in the agent overview?
image
image

- Should the Discover button add some filter? It seems that is not doing

image

- Should the module have a filter as it does in Kibana?
image
image

**Comment by asteriscos** [comment]
> Great job.
> Here are a couple of improvements / bugs:
> 
> * When selecting a field of any visualization, the tooltip that appears covers most of it being quite uncomfortable.
>   image
> * When you refresh a view, all of them are refreshed, not just the one you select.
> * When generating a pdf, in each graph, in the right margin at the bottom, a black bar appears.
>   image

This is the default behavior of Splunk visualizations tooltips. I wasn't able to alter the way it pops up.
As for the PDF, when creating a report it the visualizations don't show the line mentioned. If you could please add more info how to reproduce it I will gladly check it.
image

**Comment by asteriscos** [comment]
> I was testing the PR and I am not experiencing the bug with the reports:
> 
> image
> 
> Possible bugs:
> 
> * Should the Mitre module appear by default in the agent overview?
>   image
>   image
> * Should the Discover button add some filter? It seems that is not doing
> 
> image
> 
> * Should the module have a filter as it does in Kibana?
>   image
>   image

**Mitre Att&ck** is now a **default module**. Also the module now includes the implicit filter `rule.mitre.id{}` and is included when clicking the _Discover button_

**Review by CPAlejandro — APPROVED** [review]
Testing: LGTM!

**Pull request merged**
