### PR TITLE
Dynamic columns width in agents report

### LINKED ISSUE #1019: Agent info doesn't fit page on report
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4   | 8.1.1     | 68 |

**Description**
The agent's info doesn't fir well the page on the generated report for agent configuration.

This should be fixed. 

**Steps to reproduce**

1. Go to Agents view
2. Click on the configuration button on an active agent
3. Generate a report clicking in "PDF" button
4. Open the generated report.

**Screenshots**

image
image
image

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this fixes the columns dynamic columns width for agents PDF report.

Closes #1019 

image

### CODE REVIEW

**Review by CPAlejandro — APPROVED** [review]
I have just test it and it works properly. Nice job!
image

**Review by pablomarga — APPROVED** [review]
LGTM!

**Comment by Desvelao** [comment]
I tested the PR and it is working now.

**Review by Desvelao — APPROVED** [review]
LGTM!

**Pull request merged**
