### PR TITLE
Adapt files api endpoints

### LINKED ISSUE #1025: Migrate cluster and manager files endpoints
Hi team.
We need to migrate this API endpoints `/manager/files` and `/cluster/{node_id}/files`  corresponding to this [#wazuh/7148](https://github.com/wazuh/wazuh/issues/7148)

- [x] Migrate configuration files endpoints to `/manager/configuration` and `/cluster/{node_id}/configuration` https://github.com/wazuh/wazuh/issues/7181)
  - [x] Read
  - [x] Edit
- [x] Migrate decoder files endpoints to `/decoders/files` https://github.com/wazuh/wazuh/issues/7179
  - [x] Read
  - [x] Edit
  - [x] Delete
  - [x] Upload/import
  - [x] Link to open the file in details
- [x] Migrate rule files endpoints to `/rules/files` https://github.com/wazuh/wazuh/issues/7178
  - [x] Read
  - [x] Edit
  - [x] Delete
  - [x] Upload/import
  - [x] Link to open the file in details
- [x] Migrate list files endpoints to `/lists/files`  https://github.com/wazuh/wazuh/issues/7180
  - [x] Read
  - [x] Edit
  - [x] Delete
  - [x] Upload/import
  - [x] Export list (keys/values)

### PR DESCRIPTION
**Pull request by Desvelao**
### Description

Hi team, this PR resolves:

- Adapt the calls to endpoints about rules/decoders/files content, saving and editing
- Fixed export of CDB list keys and values

Closes #1025

### Checks
Use Wazuh API 4.1.3

- Rules
  - See file content
  - Edit and save content
  - Delete file
  - Import file
  - See file content from the rule detail
- Decoders
  - See file content
  - Edit and save content
  - Delete file
  - Import file
  - See file content from the decoder detail  
- CDB List
  - See file content
  - Edit and save content
  - Delete file
  - Import file
  - Export keys and values as `.csv` file

### CODE REVIEW

**Comment by frankeros** [comment]
An error occurs when trying to edit a Rule/Decoder file
image

**Comment by Desvelao** [comment]
### Changes
- Fixed the import/uploading files functionality
- Fixed some links in rule/decoder details to open the related file
- Fixed some HTML elements that didn't show related to deprecated fields API response object

**Review by pablomarga — APPROVED** [review]
### Rules
- [x] Create
- [x] Edit
- [x] Remove
- [x] Import
- [x] See file content from the rule detail

### Decoders
- [x] Create
- [x] Edit
- [x] Remove
- [x] Import
- [x] See file content from the decoder detail

### CBD lists
- [x] Create
- [x] Edit
- [x] Remove
- [x] Import
- [x] Export keys and values as .csv file

Everything seems to work fine, great job! LGTM!

**Review by sortiz1191 — APPROVED** [review]
### Rules
- [x] Create
- [x] Edit
- [x] Remove
- [x] Import
- [x] See file content from the rule detail

### Decoders
- [x] Create
- [x] Edit
- [x] Remove
- [x] Import
- [x] See file content from the decoder detail

### CBD lists
- [x] Create
- [x] Edit
- [x] Remove
- [x] Import
- [x] Export keys and values as .csv file

Everything is working properly. Great job! 👏

**Review by frankeros — APPROVED** [review]
tested :heavy_check_mark: 
great job!! :tada:

**Pull request merged**
