### PR TITLE
Added API alias value to registered APIs

### LINKED ISSUE #1145: [Feature request] Add tag to the Wazuh API selector
Hello team,

We need to add a `tag` or `cluster name` field to the Wazuh API selector.

## Description

When having multiple Wazuh APIs defined and using the API selector, all the APIs will be identified with the node hostname, which can make it difficult to understand to which environment it corresponds.

We believe that having a `tag` or `cluster name` field to identify the Wazuh API configured will make it easier to use the app.

Regards,
Franco Hielpos

### PR DESCRIPTION
**Pull request by mpRegalado**
closes https://github.com/wazuh/wazuh-splunk/issues/1145
This pull request adds an alias value to the API credentials database so users can assign a custom name to each of their connection. Changes include

- New field in internal database for storing the alias
- Updated frontend forms to include the alias
- Updated frontend tables to show the alias
- Updated quick settings menu to use the alias
- Updated validation methods to ensure no empty fields are submitted

### To test
**Test retrocompatibility**
These tests ensure that the two methods in `manager.py` that return API information correctly inject an `alias` value when none is present. You should launch a splunk environment with `4.2-8.1` and set up some credentials before switching to this branch to execute them.

Check  retrieving information for all APIs 
- **Given** an `API` has been configured in a previous version
- **And** the app has been updated to this version
- **When** the browser enters `settings/api`
- **Then** `API name` shows the same value as `URL`

Check retrieving information for a single API
- **Given** an `API` has been configured in a previous version
- **And** the app has been updated to this version
- **And** there is a single `API`
- **When** the user opens `Quick Settings`
- **Then** `Wazuh API` shows the same value as `URL`

**Test new features**

Show API submission form
- **Given** there is no `API`
- **When** browser navigates to `settings/api`
- **Then** `API name` input field appears along `Username`, `Password`, `URL`, and `Port`

Check validation for new API
- **Given** the browser is in `settings/api`
- **And** There is no `API`
- **When** the user submits any empty field or invalidly formatted
- **Then** an error shows up
- **And** `API` is not added

Submit an API
- **Given** the browser is in `settings/api`
- **And** There is no `API`
- **When** the user submits a valid form
- **Then** the page shows the `API` information
- **And** the `API name` field is the same as submitted

Check Quick Settings for single API
- **Given** there is a single `API`
- **When** the user opens `Quick Settings`
- **Then** `Wazuh API` shows the alias

Check edit API form
- **Given** there is an `API`
- **When** the user clicks on the `Edit API` button
- **Then** fields for `API name`, `Username`, `Password`, `URL` and `Port` are shown

Check edit API form validation
- **Given** the `Edit API` form is shown
- **When** the user submits any empty field or invalidly formatted
- **Then** an error shows up
- **And** `API` is not modified

Edit an API
- **Given** the `Edit API` form is shown
- **When** the user submits a valid form
- **Then** API info updates accordingly

Check additional API submission form
- **Given** there is at least a single `API`
- **When** the user clicks on `add new`
- **Then** fields for `API name`, `Username`, `Password`, `URL` and `Port` are shown

Check additional API submission form validation
- **Given** the `Add new API` form is shown
- **When** the user submits any empty field or invalidly formatted
- **Then** an error shows up
- **And** `API` is not added

Check adding an extra API
- **Given** the `Add new API` form is shown
- **When** the user submits a valid form
- **Then** a new API is added to the table

Check Quick Settings for multiple API
- **Given** there are multiple `API`
- **When** the user opens `Quick Settings`
- **Then** `Wazuh API` shows a dropdown menu containing the aliases for the `APIs`

Check Persistence
- **Given** there is information for `APIs` in the database
- **When** browser opens the app in a new session
- **Then** information about the `APIs` is the most updated

Check Persistence
### Screenshots
**First API Form**
image

**API table**
image

**Edit API form**
image

**Quick Settings**
image

### CODE REVIEW

**Review by gabiwassan — APPROVED** [review]
LGTM ! 🚀

**Review by frankeros — COMMENTED** [review]
LGTM! just minor changes

**Review by frankeros — APPROVED** [review]
LGTM!

**Comment by Desvelao** [comment]
**review**:

Testing:
- **suggestion**: If I click to edit the API info, the API alias is not displayed
image

- Using a Splunk user without permissions to create/edit/remove the API info into the Splunk database, throws errors
  - Create
  image
  - Update
  Setting another API alias keeps the previous alias and there are no errors or the alias is not changed

  - Delete
  This seems to be ok displaying the problem due to the user permissions:
  image

**Review by eze9252 — APPROVED** [review]
LGTM!

**Comment by Desvelao** [comment]
**review**

Testing:
- Settings > API
  - :x: If I edit an API host entry and change the API alias, the API entry selector displays the previous API alias
  
image

**Review by Desvelao — APPROVED** [review]
LGTM!

**Pull request merged**
