### PR TITLE
Fix API console to allow payloads in requests

### LINKED ISSUE #1081: Unable to create a Wazuh API user from Dev Tools
| Wazuh | Splunk | Rev |
| ------- | ------- | ----- |
| 4.1.5    | 8.1.2    | 444 |

### Description
Unable to create a Wazuh manager API's user from **Wazuh App for Splunk** -> **>_Dev Tools**

### Steps to reproduce

1. Go to `Wazuh for Splunk`
2. Click on `>_Dev Tools`
3. Try to send a `POST` request to the manager endpoint API `/security/users/` as follows:
```
POST /security/users/
{ "username": "cesar_test", 
 "password": "Pa$$word123", 
 "allow_run_as": true 
}
```
4. See **error 400 - Bad Request**:
> {
>   "error": "{'title': 'Bad Request', 'detail': \"'username=cesar_test&password=Pa%24%24word123&allow_run_as=true' is not of type 'object'\"}"
> }
5. If you execute a `GET` command in the same window to this endpoint, it works as expected and shows the users.
6. If the same `POST` is executed with `cURL` from the same server to create the API user, it works as expected:
`curl -k -X POST "https://192.168.58.136:55000/security/users" -H  "Authorization: Bearer $TOKEN"  -H  "Content-Type: application/json" -d "{\"username\":\"cesar-remote-test2\",\"password\":\"Test.1234\"}"`
> {"data": {"affected_items": [{"id": 101, "username": "cesar-remote-test2", "allow_run_as": false, "roles": []}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "User was successfully created", "error": 0}[

### Screenshots
**Error Screenshot:**
image

**Executed GET command screenshot:**
image

### Additional context
The Wazuh manager was updated from 3.x to 4.1. The same POST execution worked previously.
It seems that the Wazuh app for Splunk is sending a wrong formatted request to the API that couldn't be interpreted as an object. 
**Please find some debug logs during the API call from Dev Tools:**
> 2021/05/03 19:58:56 INFO: wazuh 192.168.58.129 "GET /manager/status" with parameters {} and body {} done in 0.059s: 200
> 2021/05/03 19:58:56 DEBUG2: Receiving headers {'Host': '192.168.58.136:55000', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjIwMDg2MTkxLCJleHAiOjE2MjAwODcwOTEsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.gYVHAdD-NP6DoT83uJnJn-k5N6ICfnZIAgsCVb2872M', 'Content-Length': '62', 'Content-Type': 'application/x-www-form-urlencoded'}
> 2021/05/03 19:58:56 DEBUG: Getting data and status code
> 2021/05/03 19:58:56 DEBUG: Decoded token {'username': 'wazuh', 'roles': [1], 'token_nbf_time': 1620086191, 'run_as': False}
> 2021/05/03 19:58:56 DEBUG2: Starting to execute request locally
> 2021/05/03 19:58:56 DEBUG2: Finished executing request locally
> 2021/05/03 19:58:56 DEBUG2: Time calculating request result: 0.048s
> 2021/05/03 19:58:56 DEBUG2: Receiving parameters {}
> 2021/05/03 19:58:56 DEBUG2: Starting to execute request locally
> 2021/05/03 19:58:56 DEBUG2: Finished executing request locally
> 2021/05/03 19:58:56 DEBUG2: Time calculating request result: 0.002s
> 2021/05/03 19:58:56 INFO: wazuh 192.168.58.129 "POST /security/users/" with parameters {} and body {} done in 0.053s: **400**

**Some more debug logs during the API call from cURL:**
> 2021/05/03 20:03:27 DEBUG2: Receiving parameters {'username': 'cesar-remote-test3', 'password': '*'}
> 2021/05/03 20:03:27 DEBUG2: Starting to execute request locally
> 2021/05/03 20:03:27 DEBUG2: Finished executing request locally
> 2021/05/03 20:03:27 DEBUG2: Time calculating request result: 0.134s
> 2021/05/03 20:03:27 INFO: wazuh 192.168.58.129 "POST /security/users" with parameters {} and body {"username": "cesar-remote-test3", "password": "*"} done in 0.190s: **200**

Thanks and best regards,
Cesar Moreno.

### PR DESCRIPTION
**Pull request by asteriscos**
## Summary

Closes #1081 

This PR fixes a problem of the API console, where the requests with payload won't be sent using the correct content type, causing the request to fail.

https://user-images.githubusercontent.com/15186973/178725754-ebc22e79-6de9-4010-977b-e71652492cb7.mp4

## Refactor of the API console

In order to solve this, a new way to send requests has been implemented, which consists on using a hierarchy of classes to model each kind of request and response expected. With this approach, we ensure that the request is valid before sending it. In the same way, the response is also modeled, ensuring that the properties we need exists and are in a valid state (this is what class constructors are for), getting rid of errors related to the reading of undefined properties, and repeated validation of the response object. This is all centralized now.

In order to better solve this issue, I needed to split the monstrous Angular controller into smaller pieces, in order to better understand its logical structure and flow. In direct benefit, much of this flow and logic has been re-implemented using a simpler approach, and lots of refactorings has been done, improving the code legibility and understandability. 

### What's been done

- More descriptive names are used for class members, variables and methods. 
- The controller has been split into smaller pieces, making it easier to read and maintain.
- Every method has been properly documented.
- A hierarchy of classes has been added to model each HTTP request available.

request_models

### Test 1: common use

Test that any available API endpoint works properly. The followings requests can be used:

```
GET /security/users/

POST /security/users/
{
	"username": "user_test",
	"password": "Pa$$word123"
}

PUT /security/users/100/
{
	"password": "pa$$word"
}

PUT /security/users/100/
{
	"password": "A$61a78e492"
}

DELETE /security/users?user_ids=100

GET /agents/999/key
GET /bsdg
GET /syscollector/000/packages?search=ssh&limit=1

GET /mitre/techniques

GET /agents/
{
	"invalid": "query param"
}
```

### Test 2: edge cases

Test that unexpected errors are handled properly, for example, when a timeout happens.

The `GET /mitre/techniques` timeouts every time on a fresh environment. To force this behavior, reduce the App's timeout setting, then down any manager node (Docker), and  rebuild it, so its cache is cleared. Finally go to the API console and launch the request.

### Test 3: previous functionality

Also, test that any other functionality keeps working, as:
- Documentation links, pointing to the correct section and version.
- Windows resizing.
- The play and documentation links are hidden if no valid request is selected. They move to the selected request group accordingly.
- Shift + Enter key combination sends a request.
- Arrow keys work properly.

### CODE REVIEW

**Review by AlexRuiz7 — APPROVED** [review]
Suggestion: run prettier to format the code and avoid large lines, so the line 978 becomes:
```js
  const payload =
    method != 'GET'
      ? { content: JSON.stringify(JSONraw), origin: 'json' }
      : JSONraw
```
Much easier to read. Otherwise, it LGTM!


--------------
CR ✔️ 
Test ✔️

**Comment by AlexRuiz7** [comment]
Needs a Changelog entry.

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]
- Prettier.
- Changelog entry.

**Review by AlexRuiz7 — DISMISSED** [review]
LGTM!

**Review by yenienserrano — APPROVED** [review]

**Review by yenienserrano — DISMISSED** [review]
Test: ✔️ 
CR: ✔️

**Comment by AlexRuiz7** [comment]
Rebased onto 4.3

**Comment by AlexRuiz7** [comment]
There are some side effects that need to be analyzed

https://github.com/wazuh/wazuh-splunk/issues/1081#issuecomment-1145905499

**Review by asteriscos — COMMENTED** [review]
Looks great, good job :+1: 

Test: :heavy_check_mark: 

image

**Review by Desvelao — APPROVED** [review]
**review**:
Code :heavy_check_mark: 
Test :heavy_check_mark:

**Review by yenienserrano — APPROVED** [review]
CR: ✔️ 
Test: ✔️

**Pull request merged**
