### PR TITLE
Fixed group report false configuration parameter

### LINKED ISSUE #1247: PDF group reports are blank
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.4     | 444 |

**Description**
Created PDF group reports are blank.

**Steps to reproduce**

1. Go to `Management / Groups`
2. Click on a group to select it
3. Click on the PDF report button
4. Generate a PDF report
5. Go to `Management / Reporting`
6. See the blank report

**Screenshots**
Peek 2022-02-09 19-54

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this fixes a python exception when some PDF report options where not selected. Also fixes the documentation url to use current version instead of a fixed one.

Closes #1247 #1093

To test it:

- Go to Management / Groups
- Edit a group configuration with some example configuration like the following and save it:
`<agent_config name="agent_name">
	<localfile>
		<location>/var/log/my.log</location>
		<log_format>syslog</log_format>
	</localfile>
</agent_config>
<agent_config os="Linux">
	<localfile>
		<location>/var/log/linux.log</location>
		<log_format>syslog</log_format>
	</localfile>
</agent_config>
<agent_config profile="database">
	<localfile>
		<location>/var/log/database.log</location>
		<log_format>syslog</log_format>
	</localfile>
</agent_config>`
- Select that group a generate different  PDF report with different options selected

image

### CODE REVIEW

**Review by AlexRuiz7 — APPROVED** [review]
CR ✔️ 
Test ✔️

**Review by Desvelao — APPROVED** [review]
**review**
Test ✅

**Review by Machi3mfl — APPROVED** [review]
CR ✅
Test ✅

**Comment by Machi3mfl** [comment]
Fixed 
Screen Shot 2022-02-16 at 14 13 23

**Pull request merged**
