### PR TITLE
Reload triggers for custom conf files.

### PR DESCRIPTION
**Pull request by larrys**
This fixes an app inspection failure for Splunk Cloud

### CODE REVIEW

**Comment by AlexRuiz7** [comment]
Hello @larrys 

Thank you for the contribution.

This is interesting as these settings allow the configuration changes on the App to take effect without restarting Splunk.

Unfortunately, I've tried these settings before without success. We will try this PR nevertheless and include it if it proves to work.

If you have some advice to test whether the reload triggers work it would greatly help.

**Comment by larrys** [comment]
I am going off the output of `splunk-appinspect inspect --mode precert SplunkAppForWazuh` and trying to fix things so we can get this deployed to Splunk Cloud. Although there seems to be some other issues that might need more work for this to be Splunk Cloud certified.

As for the triggers, https://docs.splunk.com/Documentation/Splunk/latest/Admin/Appconf#.5Btriggers.5D has some info. I've not really dealt with custom conf files, so I went with simple.

**Comment by larrys** [comment]
Looks like this PR will fix one of them...
```
[  F  ] - check_reload_trigger_for_all_custom_confs - Check that custom conf files have a corresponding 
            reload trigger in app.conf Without a reload trigger the app will 
            request a restart on any change to the conf file, which may be a 
            negative experience for end-users. ```

The other is since you have exposed 
```
[splunktcp://9997]
connection_host = ip
```

In the inputs.conf, which should not be there for Splunk Cloud, and for any existing Splunk instance, it should be up to the admin to enable that, if they have not already.

**Review by AlexRuiz7 — APPROVED** [review]

**Comment by AlexRuiz7** [comment]
> Looks like this PR will fix one of them...
> 
> ```
> [  F  ] - check_reload_trigger_for_all_custom_confs - Check that custom conf files have a corresponding 
>             reload trigger in app.conf Without a reload trigger the app will 
>             request a restart on any change to the conf file, which may be a 
>             negative experience for end-users. 
> ```

I can confirm it works, many thanks.

We'll try to fix the remaining failed checks as soon as possible

**Pull request merged**
