### PR TITLE
Error message on agents tab

### LINKED ISSUE #1299: Error message on Agents tab
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3.0   | 8.2.2     |  4303 |

**Description**
I set up Splunk indexer node and another node with Manager and forwarder to test.
Without agents the message:
```
  Unable to retrieve results. It may be due to a connection problem with the Splunk forwarder, please try restarting this service. 
```
Always appears when tab `Agents` is selected.

**Steps to reproduce**

1. Go to `Agents` without agents configured.
2. See the error.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by yenienserrano**
**Description:**

When connecting to the forwarder, sometimes get an error message saying  `Unable to retrieve results. It may be due to a connection problem with the Splunk forwarder, please try restarting this service.`  which does not have to appear when the connection is made.

**Pre-conditions:**

have connection with the forwarder

**Test:**

1. log in
2. Navigate to `Agents`
3. See if the error appears
4. Navigate to `Security Events`
5. See if the error appears
6. Repeat several times

**issue:**

- #1299 1299

**Screenshots**

https://user-images.githubusercontent.com/63758389/166700807-2b3240c3-9a7e-4e92-bb7e-d01dd690c59d.mp4

### CODE REVIEW

**Review by chantal-kelm — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark:

**Comment by Desvelao** [comment]
The proposed solution using a `setTimeout` seems not to be the good one. We should research more and try to apply another solution.

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]
Revert the changes to the package.conf file

**Comment by AlexRuiz7** [comment]
Closed in favor of #1320

**Pull request closed without merging**
