### PR TITLE
Allow partial string search in main search

### LINKED ISSUE #1012: Cannot seach by incomplete name
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4   | 8.1.1     | 68 |

**Description**
Hi!
The agent's preview search box only finds agents by exact name. It doesn't search coincidences.
If I want to search all agents with a prefix name I couldn't do it.

**Steps to reproduce**

1. Go to agents preview
2. Click on search box
3. Set name tag and put partial name

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this changes the equal operator to _like_ operator, which allows partial string search when filtering by tag.

Closes #1012

### CODE REVIEW

**Comment by CPAlejandro** [comment]
Good job, I've been testing it for numeric and alphanumeric fields and it gets the results perfectly!

**Review by eze9252 — APPROVED** [review]
LGTM!

**Review by pablomarga — APPROVED** [review]
LGTM! Good job!

**Review by frankeros — APPROVED** [review]
tested :heavy_check_mark: 
LGTM!

**Pull request merged**
