### PR TITLE
Feat/security crud policies

### PR DESCRIPTION
**Pull request by gabiwassan**
Hi team,
This PR added new CRUD of Policies on the security section.

image
image
image

Close: #1152

### CODE REVIEW

**Comment by AlexRuiz7** [comment]
The UI allows to modify reserved policies. On save, an error message is shown, as the policy cannot be edited.

The UI should not allow to modify the reserved policies at any time, as results on a waste of time for the user and generates a bad UX
image

**Comment by gabiwassan** [comment]
> negative_squared_cross_mark The table sorting takes too long to load due to an undefined error, has seen on the gif below. This happens for **policy.actions**, **policy.resources** and **policy.effect**
> 
> bulb Also, these 3 columns could be name as Policy Actions, Policy Resources and Policy Effect.
> 
> Policies

- Currently, we cannot change the names of the columns, since they are the ones that the API brings (this is improved when we create a new wz-table component)
- The API responds that the ordering by these fields cannot be requested:
`error: "{'title': 'Bad Request', 'detail': 'Not a valid sort field', 'remediation': '**Please, use only allowed sort fields: Allowed sort fields: policy, name, id, roles**. Wrong fields: policy.actions', 'dapi_errors': {'master-node': {'error': 'Not a valid sort field '}}, 'error': 1403}"`
**Please, use only allowed sort fields: Allowed sort fields: policy, name, id, roles** 🤔 

We could order it in memory in the front-end, but as I said before, the current component does not allow us this.

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]
## Test
✔️ Create
✔️ Read
✔️ Update
✔️ Delete

However, if a new policy matches an already existing policy (with different names), it cannot be created. **I guess this is a feature and not a bug**, but just to be sure.
Here, the new policy `agent_all_resourceless_test` defines the same actions and resources as the existing `agents_all_resourceless`policy.
image


## Bugs
* Confirmation form shows for each equal resource. Only the clicked one is actually deleted. I'm not even sure if it should allow the same `action:resource` be defined more than once.
image

* Empty policy can be created.
image

* No resources suggested for `group:read` action. Should show `group:id`, but `*:*` is shown instead.
image

## Improvements
- Inline CSS.
- Last reserved policy shows the edit and remove actions.
image

- policy.actions, policy.resources, policy.actions table headers could be improved (**pull my commit**)
image

**Comment by gabiwassan** [comment]
Added new validation and toast warning to prevent repeat resources:
image

**Review by yenienserrano — APPROVED** [review]
CR: :heavy_check_mark:

Test: :heavy_check_mark:

**Review by eze9252 — APPROVED** [review]
LGTM!

**Pull request merged**
